DROP TYPE IF EXISTS users_status_enum;
DROP TYPE IF EXISTS users_role_enum;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS transaction;